## 数据创建与访问

导入Numpy

In [27]:
import numpy as np

要求：创建10x10数组
1. 数组元素为服从标准正态分布的随机数

In [28]:
arr = np.random.randn(10, 10)
print(arr)

[[ 1.99226683  0.42259816 -0.05233986 -0.50745306  0.66800765 -2.08527363
   0.00292974  1.43603991  0.94513803  0.29826398]
 [-0.88011435  1.39580512  1.7702214  -0.27774672  0.25958783 -0.30825358
  -1.90837019  0.99610785 -0.69123263  1.89762728]
 [-0.83042712 -1.85214487 -0.06447878 -0.10538762  0.06522311 -0.09304871
  -0.60715996 -1.7263651  -0.30265855 -0.32610498]
 [ 0.56227983  0.30270648  1.40174627  0.24307229 -0.11198576 -1.01182897
   0.06098239  1.73236558  0.86733047  0.51267843]
 [-1.31946807  0.6050121   0.91562717  1.92863463  1.63971154  0.00594012
  -0.21326767 -1.34578686 -0.02262042 -0.27141033]
 [ 0.79225122 -1.22764472 -0.59715146  0.24518344  1.44589122 -1.79314163
   1.13601321 -1.33400934 -1.00523559  0.17772947]
 [-1.95797248 -0.04960774 -1.08552338  0.84321769  1.87275183 -0.82374692
  -0.91369772 -0.91662946  1.83805096  1.65116665]
 [ 1.43560916 -0.07596719  0.33543825 -0.18400472 -0.17023105 -0.84373623
  -1.29998337 -0.22078544 -0.25060441 -0.73727454]


2. 对数组元素进行数据类型转换（float转int），并进行转置

In [29]:
arr = arr.astype(int).T
print(arr)

[[ 1  0  0  0 -1  0 -1  1  0 -1]
 [ 0  1 -1  0  0 -1  0  0 -1  0]
 [ 0  1  0  1  0  0 -1  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  1  1  1  0  1 -1]
 [-2  0  0 -1  0 -1  0  0  1  0]
 [ 0 -1  0  0  0  1  0 -1  0  0]
 [ 1  0 -1  1 -1 -1  0  0  0  0]
 [ 0  0  0  0  0 -1  1  0  0  0]
 [ 0  1  0  0  0  0  1  0  0  0]]


3. 查看数组的数据类型

In [30]:
print(arr.dtype)

int64


4. 查看数组的内存占用情况

In [31]:
print(arr.nbytes)

800


5. 使用一行代码找出数组中所有的偶数，并存入一个一维数组中

In [32]:
arr1D = arr[arr % 2 == 0]
print(arr1D)

[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0 -2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]


## 基本矩阵操作与运算

要求：
1. 创建主对角线都是3的5x5矩阵matr（0-4行，0-4列）

In [33]:
matr = np.matrix(np.diag([3,3,3,3,3]))
print(matr)

[[3 0 0 0 0]
 [0 3 0 0 0]
 [0 0 3 0 0]
 [0 0 0 3 0]
 [0 0 0 0 3]]


2. 交换matr第一列与第二列，构成matr1

In [34]:
matr1 = matr[:,[1,0,2,3,4]]
print(matr1)

[[0 3 0 0 0]
 [3 0 0 0 0]
 [0 0 3 0 0]
 [0 0 0 3 0]
 [0 0 0 0 3]]


3. 交换matr第二行与第三行，构成matr2

In [35]:
matr2 = matr[[0,2,1,3,4],:]
print(matr2)

[[3 0 0 0 0]
 [0 0 3 0 0]
 [0 3 0 0 0]
 [0 0 0 3 0]
 [0 0 0 0 3]]


4. 判断matr1和matr2否有任何元素不同，计算不同元素的个数，找出不同元素的位置

In [36]:
diff_count, diff_indices = np.sum(matr1 != matr2),np.argwhere(matr1 != matr2)
print(diff_count,"\n",diff_indices)

6 
 [[0 0]
 [0 1]
 [1 0]
 [1 2]
 [2 1]
 [2 2]]


5. 计算matr1和matr2的相乘结果

In [37]:
print(np.dot(matr1, matr2))

[[0 0 9 0 0]
 [9 0 0 0 0]
 [0 9 0 0 0]
 [0 0 0 9 0]
 [0 0 0 0 9]]


6. 计算matr1和matr2对应元素相乘的结果

In [38]:
print(np.multiply(matr1, matr2))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 9 0]
 [0 0 0 0 9]]


7. 将matr1和matr2按行拼接

In [39]:
print(np.hstack((matr1, matr2)))

[[0 3 0 0 0 3 0 0 0 0]
 [3 0 0 0 0 0 0 3 0 0]
 [0 0 3 0 0 0 3 0 0 0]
 [0 0 0 3 0 0 0 0 3 0]
 [0 0 0 0 3 0 0 0 0 3]]


## 使用Numpy进行统计分析
要求：
1. 使用numpy生成6行6列的二维数组arr，值为1-100随机整数

In [40]:
arr = np.random.randint(1, 101, size = [6, 6])
print(arr)

[[18  4  6  4 49 59]
 [34 97 33 18  8 75]
 [43 65 78 31 43 31]
 [52 66 66 44 11 96]
 [44  3  5 87 96 76]
 [25 96 35 84 25 32]]


2. 找出arr每列的最大值

In [41]:
print(np.max(arr, axis=0)) 

[52 97 78 87 96 96]


3. 找出arr每行的最小值

In [42]:
print(np.min(arr, axis=1)) 

[ 4  8 31 11  3 25]


4. 计算arr每个元素的出现次数

In [43]:
unique, counts = np.unique(arr, return_counts=True)
print("列表中元素与次数一一对应",unique, counts)

列表中元素与次数一一对应 [ 3  4  5  6  8 11 18 25 31 32 33 34 35 43 44 49 52 59 65 66 75 76 78 84
 87 96 97] [1 2 1 1 1 1 2 2 2 1 1 1 1 2 2 1 1 1 1 2 1 1 1 1 1 3 1]


5. 获取arr第3行每个元素的大小排名

In [44]:
rank = np.argsort(np.argsort(arr[2]))+1
print("从小到大排名",rank)

从小到大排名 [4 5 6 1 3 2]
[3 5 4 0 1 2]


6. 去除arr中重复的行

In [45]:
arr = np.unique(arr, axis=0)
print(arr)

[[18  4  6  4 49 59]
 [25 96 35 84 25 32]
 [34 97 33 18  8 75]
 [43 65 78 31 43 31]
 [44  3  5 87 96 76]
 [52 66 66 44 11 96]]


7. 从arr中第4行不放回的抽出3个元素

In [46]:
sample = np.random.choice(arr[3], 3, replace=False)
print(sample)

[43 31 31]


8. 提取arr第5行中不含第1行数据的数据

In [47]:
result = arr[4, ~np.isin(arr[4], arr[0])]
print(result)

[44  3  5 87 96 76]


9. 将arr中小于10的元素修改为Nan，生成arr2

In [48]:
arr2 = np.where(arr < 10, np.nan, arr)
print(arr2)

[[18. nan nan nan 49. 59.]
 [25. 96. 35. 84. 25. 32.]
 [34. 97. 33. 18. nan 75.]
 [43. 65. 78. 31. 43. 31.]
 [44. nan nan 87. 96. 76.]
 [52. 66. 66. 44. 11. 96.]]


10. 删除arr2中含有Nan的列

In [49]:
arr2 = arr2[:, ~np.isnan(arr2).any(axis=0)]
print(arr2)

[[18. 59.]
 [25. 32.]
 [34. 75.]
 [43. 31.]
 [44. 76.]
 [52. 96.]]
